from scipy import constants





# print(constants.yotta)
# print(constants.zetta)
# print(constants.exa)
# print(constants.peta)
# print(constants.tera)
# print(constants.giga)
# print(constants.mega)



# print(constants.kibi)
# print(constants.mebi)
# print(constants.gibi)
# print(constants.tebi)
# print(constants.pebi)
# print(constants.exbi)
# print(constants.zebi)
# # print(constants.yobi)

# print(constants.gram)
# print(constants.metric_ton)
# print(constants.grain)
# print(constants.lb)
# print(constants.pound)
# print(constants.oz)
# print(constants.ounce)
# print(constants.stone)
# print(constants.long_ton)
# print(constants.short_ton)
# print(constants.troy_ounce)
# print(constants.troy_pound)
# print(constants.carat)
# print(constants.atomic_mass)
# print(constants.m_u)
# print(constants.u)
# print(constants.mu_0)


# print(constants.degree)
# print(constants.arcmin)
# print(constants.arcminute)
# print(constants.arcsec)
# print(constants.arcsecond)

# print(constants.minute)
# print(constants.hour)
# print(constants.day)
# print(constants.week)
# print(constants.year)
# print(constants.Julian_year)
# print(constants.light_year)

print(constants.inch)
print(constants.foot)
print(constants.yard)
print(constants.mile)
print(constants.mil)
print(constants.pt)
print(constants.point)
print(constants.survey_foot)
print(constants.survey_mile)
print(constants.nautical_mile)
print(constants.fermi)
print(constants.angstrom)
print(constants.micro)
print(constants.au)
print(constants.astronomical_unit)
print(constants.light_year)
print(constants.parsec)
